POST http://localhost:8080/accounts
Content-Type: application/json

{
    "firstName": "Anuj",
    "lastName": "Dev",
    "email": "anuj@example.com"
}

###

GET http://localhost:8080/accounts

###

PATCH http://localhost:8080/accounts
Content-Type: application/json

{
    "id": "d56247a9-8cb8-42e4-a4df-cff36d006711",
    "firstName": "Anuj",
    "lastName": "Dev2",
    "email": "anuj@example.com",
    "providerId": "cus_PtKEK3F03RkcFe",
    "providerType": "STRIPE"
}
