# @name create_user
POST http://localhost:8080/accounts
Content-Type: application/json

{
    "firstName": "Rohan2",
    "lastName": "Yadav2",
    "email": "rohan@example.com"
}

###

GET http://localhost:8080/accounts

###

PATCH http://localhost:8080/accounts
Content-Type: application/json

{
    "id": "1b2243da-4335-413d-bf4e-23f88f3e61d0",
    "firstName": "Rohan2-updated",
    "lastName": "Yadav",
    "email": "rohan@example.com",
    "providerId": "dfdf",
    "providerType": "STRIPE"
}
