version: "3"

services:
  # midas-app:
  #   image: midas-app:latest
  #   container_name: midas-app
  #   build:
  #     context: .
  #   depends_on: 
  #     - postgres
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/mydatabase
  #     SPRING_DATASOURCE_USERNAME: myuser
  #     SPRING_DATASOURCE_PASSWORD: secret
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - midas-network
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - 5432:5432
    networks:
      - midas-network
  pgadmin:
    image: dpage/pgadmin4:8.5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on: 
      - postgres
    ports:
      - 5050:80
    networks:
      - midas-network
  # temporal:
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DB=postgres
  #     - DB_PORT=5432
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PWD=secret
  #     - POSTGRES_SEEDS=postgres
  #     - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
  #   image: temporalio/auto-setup:1.23.0
  #   networks:
  #     - midas-network
  #   ports:
  #     - 7233:7233
  #   volumes:
  #     - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  #   labels:
  #     kompose.volume.type: configMap
  # temporal-admin-tools:
  #   depends_on:
  #     - temporal
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:7233
  #     - TEMPORAL_CLI_ADDRESS=temporal:7233
  #   image: temporalio/admin-tools:1.23.0
  #   networks:
  #     - midas-network
  #   stdin_open: true
  #   tty: true
  # temporal-ui:
  #   depends_on:
  #     - temporal
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:7233
  #     - TEMPORAL_CORS_ORIGINS=http://localhost:3000
  #   image: temporalio/ui:2.22.3
  #   networks:
  #     - midas-network
  #   ports:
  #     - 8888:8080
networks:
  midas-network:
    driver: bridge
